# IP passée en ligne de commande : -e ansible_host=$(terraform output -raw ec2_public_ip)

[webservers]
meditrack-web

[webservers:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3
